kind: ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  namespace: backyard
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nlachter@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
