apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: website
  name: production
  labels:
    app: production
spec:
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
        - name: production
          image: dockercloud/hello-world:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: website
  name: production-backend
  labels:
    app: production
spec:
  type: NodePort
  selector:
    app: production
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: website
  name: production-website-nlachter-tls
spec:
  secretName: production-website-nlachter-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: website-nlachter.com
  dnsNames:
    - website.k8s.nlachter.fr
  acme:
    config:
      - http01:
          ingress: production
        domains:
          - website.k8s.nlachter.fr
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: website
  name: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: production # A static IP must exist with this name
  labels:
    app: production
spec:
  backend:
    serviceName: production-backend
    servicePort: 80
  tls:
    - secretName: production-website-nlachter-tls
      hosts:
        - website.k8s.nlachter.fr
