apiVersion: v1
kind: Service
metadata:
  namespace: website
  name: production-backend
  labels:
    app: production
spec:
  type: NodePort
  selector:
    app: production
  ports:
    - port: 80
      targetPort: 80
