apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  namaspace: website
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: nlachter@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  namaspace: website
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: nlachter@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
