apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: website
  name: production-website-nlachter-tls
spec:
  secretName: production-website-nlachter-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: main-endpoint-website-k8s.nlachter.fr
  dnsNames:
    - main-endpoint-website-k8s.nlachter.fr
    - second-endpoint-website-k8s.nlachter.fr
  acme:
    config:
      - http01:
          ingress: production-ingress
        domains:
          - main-endpoint-website-k8s.nlachter.fr
          - second-endpoint-website-k8s.nlachter.fr
