version: "2"
services:

  nginx:
    image: 'nginx:latest'
    links:
      - 'php:FPM-SERVICE'
    ports:
      - '80:80'
    volumes:
      - /srv/symfony
      - './vhost.conf:/etc/nginx/conf.d/default.conf:ro'
    volumes_from:
      - php

  php:
    build:
      context: ..
      args:
        - WORKDIR=/srv/symfony
    volumes:
      - /srv/symfony
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=null
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=tests
      - MAILER_TRANSPORT=mailer
      - MAILER_HOST=null
      - MAILER_USER=null
      - MAILER_PASSWORD=null
      - SECRET=ThisSecretIsNotSecretAnymore
